
class FabonacciNumber():
    """ This class defines fabonacci number pattern. Fibanacci is a number pattern in which each number is a sum of
    preceeding two numbers. Fabonacci number starts at 0 and 1. """

    def __init__(self, num):
        """ It defines a fabonacci number pattern and num is the number upto which a fabonacci pattern will be 
        generated. """
        self.num = num

    def fabonacci_pattern(self):
        """ This function creates the fabonacci number pattern. """

        initial_fab = [0, 1]
        if self.num > 2:
            count = 2
            while count < self.num:
                # for val in initial_fab:
                sum = initial_fab[-2] + initial_fab[-1]
                initial_fab.append(sum)
                count += 1
        return initial_fab

    def display_fabonacci_numbers(self):
        """ This function displays the fabonacci numbers generated by the above function. """
        fab_nums = FabonacciNumber.fabonacci_pattern(self)
        for val in fab_nums:
            print(val, end=" ")
        return " "

obj = FabonacciNumber(5)
fab_pattern = obj.fabonacci_pattern()
fab_display = obj.display_fabonacci_numbers()
print(fab_display)
# print(fab_pattern)




